motion_id = diveLeft
"motion falling on the left side (field RHYP missing)
label start

stiffness 30  30  *  *  *  *  0  0  0   0  0   0  0  0  100  100   100   100   100   100  0  100   100   100   100   100  0

"   HY     HP    LSP    LSR    LEY    LER  _LWY_  _LH_     RSP    RSR    REY    RER  _RWY_   _RH_   LHYP    LHR    LHP    LKP    LAP    LAR   RHYP    RHR    RHP    RKP    RAP    RAR Int  Dur
   -20     25    -50     75    -15    -20     0      0      50    -21    0.2     15     0      0      0       0    -70    121    -45     40     -      10    -40     80    -40     40   1  200
   -20     25    -100    60    -15    -20     0      0       0      0      0      0     0      0    -13     -19    -90    121    -68      5     -       1    -20     47    -22     25   1  400
   -20     25    -100     60    -15    -20     0      0       0      0      0      0     0      0    -13     -19    -90    121    -68      5     -       1    -20     47    -22     25   0  10000


stiffness  60  60  60   60   60   60  0   0  60   60   60   60   0  0  60    60   60    60  60   60  0   0  60  60   60   60  0
     0      0   -105      0      0      0     0      0     00      0      0      0     0      0      0       0      0      0      0      0     -       0      0      0      0      0   1  400

stiffness  60  60  60   60   60   60  0   0  60   60   60   60   0  0  60    60   60    60  60   60  0  60  60   60   60  60  0
     0      0   -105     0       0      0     0      0     0      0      0      0     0      0      0       0      0      0      0      0     -       0      0      0      0      0   1  8000

stiffness  60  60    100    100    100     100    0   0   0     0     0     0    0  0   0      100     100      100    0     0   0   100   100     100     0      0  0
     0      0   -105     76      0      0     0      0     -90     0       0      0     0      0      0      45     30      0      0      0     -      45     30      0      0      0   1  300

stiffness  60  60    100    100    100     100    0   0   0     0     0     0    0  0   0      100     100      100    0     0  0    100   100     100     0      0  0
     0      0     0     -20    -86      0     0      0     -90      0      0      0     0      0      0      45     30      0      0     0      -      45     30      0      0      0   1  300

stiffness  60  60    100    100  30     100    0   0   0     0     0     0    0  0   0      100     0      0    0     0  0    0   0     0     0      0  0
     0      0   105    -20     -80    -88     0      0     -90      0      0      0     0      0      0       0      0      0      0     0      -       0      0      0      0      0   1  300
  
stiffness  60  60    100    100  30     100    0   0   0     0     0     0    0  0   0      100     0      0    0     0   0   0   0     0     0      0  0
     0      0    105   -20     -80    -88     0      0     -60      0      0      0     0      0      0       0      0       0     0     0      -       0      0      0      0      0   1  100

stiffness  60  60    100    100  30     100    0   0   0     0     0     0    0  0   0      100     0      0    0     0   0   0   0     0     0      0  0
     0      0    105    10     -90      0      0     0      0       0      0      0     0      0      0       0      0       0     0     0      -       0      0      0      0      0   1  200

stiffness  60  60    0    100  30     100    0   0   0     0     0     0    0  0   0      100     0      0    0     0   0       0     0     0      0       0  0
    0       0    100    60     -90      0     0      0     80       0      0      0      0     0      0       0      0       0     0     0      0       0      0      0      0      0   1  200
transition allMotions extern start
