motion_id = diveRight
"motion falling on the right side (field RHYP missing)
label start


stiffness 30  30   0    0     0     0     0   0   *    *    *    *   0   0   100      100     100     100     100      100  *   100    100     100      100      100  0

"   HY     HP    LSP    LSR    LEY    LER  _LWY_  _LH_      RSP   RSR    REY    RER  _RWY_   _RH_   LHYP    LHR    LHP    LKP    LAP    LAR   RHYP    RHR    RHP    RKP    RAP    RAR  Int  Dur
    20	   25     0  	 0   -0.2     -15    0      0      -60   70    15      20    0       0      0        0    -40    80     -40    -40     -      0     -70    121    -45    -40    1  200
    20     25     0      0      0      0     0      0      -60   50    15      20    0       0     -5        0    -20    47     -22    -25     -     -10     -90    121    -68     -5    1  400
label repeat
    20	   25	  0      0      0      0     0      0  	   -60   50    15      20    0       0     -10       0    -20    47     -22    -25     -     -10     -90    121    -68     -5    0  10000

transition  diveRight diveRight repeat

transition allMotions extern start
  
   
 
