motion_id = fallLeft
label start
"   HY     HP    LSP    LSR    LEY    LER  _LWY_  _LH_     RSP    RSR    REY    RER  _RWY_   _RH_   LHYP    LHR    LHP    LKP    LAP    LAR   RHYP    RHR    RHP    RKP    RAP    RAR Int  Dur
   0.0   -18.6  148.2  18.2  -119.3  -40.8 13.5   29.0    147.8   -17.1  117.6  40.6  16.0   30.0   18.0    3.0    21.0   8.0    2.8    4.0   18.0    1.0   21.0    -8.0   3.8    2.0   1 1000
transition allMotions extern start
